site_name: CrowdTask 文档中心

site_url: http://www.crowdtask.cn

#repo_url: https://github.com/navyfeng/crowdtask_docs

docs_dir: sources

site_dir: doc

theme_dir: themes/mkdocs

theme_center_lead: false

theme: mkdocs

use_directory_urls: false

#include_search: true

include_next_prev: false

copyright: Copyright &copy; 2015, CrowdTask

author: navyfeng
pages:
- 文档首页:
    - '文档首页': 'index.md'

- 开发者指南:
    - '基本概念': 'guide/base.md'
    - '高级功能': 'guide/advance.md'
    - '数据安全': 'guide/datasecurity.md'

- API说明:
    - 'API概述': 'api/index.md'
    - '任务': 'api/task.md'
    - '结果': 'api/taskresult.md'

- SDK&代码示例:
    - '代码示例': 'downloads/index.md'
    - 'SDK&代码示例': 'downloads/code/java.md'

- 常见问题:
   - 'FAQ': 'faq/index.md'

# theme: mkdocs
