site_name: CrowdTask 文档中心

site_url: http://www.crowdtask.cn

repo_url: https://github.com/navyfeng/crowdtask_docs

docs_dir: sources

site_dir: doc

theme_dir: themes/mkdocs

theme_center_lead: false

theme: mkdocs

use_directory_urls: false

include_search: true

include_next_prev: false

copyright: Copyright &copy; 2015, CrowdTask

author: navyfeng

pages:
- [index.md, '文档首页', '文档首页']

- [guide/base.md, '开发者指南', '基本概念']
- [guide/advance.md, '开发者指南', '高级功能']
- [guide/datasecurity.md, '开发者指南', '数据安全']
- [guide/qualitycontrol.md, '开发者指南', '质量控制']

- [api/index.md, 'API说明', '规则']
- [api/task_create.md, 'API说明', '任务创建']
- [api/taskresult.md, 'API说明', '任务结果']
- [api/taskresult_reject.md, 'API说明', '队列状态']
- [api/project.md, 'API说明', '项目状态']
- [api/task.md, 'API说明', '任务状态']

- [downloads/index.md, 'SDK&代码示例', '代码示例']
- [downloads/code/java.md, 'SDK&代码示例','Java']

- [faq/index.md, '常见问题', 'FAQ']


# theme: mkdocs
